name: Build Docusaurus (Yarn) → Publish to web-Doc

on:
  push:
    branches: [ master ]          # 若默认分支不是 main，请改成你的分支名
  workflow_dispatch:

permissions:
  contents: read                # 读取代码即可；推送由凭据控制

concurrency:
  group: "publish-webdoc"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    # 将 secrets 先映射到 env，便于在 if: 表达式里安全使用
    env:
      DEPLOY_KEY_WEBDOC: ${{ secrets.DEPLOY_KEY_WEBDOC }}        # 可为空；若组织禁用 Deploy Keys，这个就留空
      PUBLISH_TOKEN_WEBDOC: ${{ secrets.PUBLISH_TOKEN_WEBDOC }}  # Fine-grained PAT（仅对 VoidWorks-online/web-Doc 授权）

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      # Yarn Berry 缓存（仓库存在 .yarnrc.yml 时启用）
      - name: Cache Yarn Berry artifacts
        if: hashFiles('.yarnrc.yml') != ''
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            .yarn/unplugged
            .yarn/build-state.yml
            .pnp.cjs
            .pnp.loader.mjs
          key: yarn-berry-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-berry-

      - name: Enable Corepack (Yarn >= 2)
        run: corepack enable

      - name: Yarn install
        run: |
          if [ -f .yarnrc.yml ]; then
            yarn --version
            yarn install --immutable
          else
            yarn --version
            yarn install --frozen-lockfile
          fi

      - name: Build Docusaurus
        # 如果站点在子目录（如 website/），加 working-directory，并把下方 publish_dir 改成 website/build
        run: yarn build

      # —— 发布到另一个仓库（VoidWorks-online/web-Doc）的 gh-pages 分支 ——
      # 路线 A：Deploy Key（若组织允许）
      - name: Publish to VoidWorks-online/web-Doc via Deploy Key
        if: ${{ env.DEPLOY_KEY_WEBDOC != '' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ env.DEPLOY_KEY_WEBDOC }}
          external_repository: VoidWorks-online/web-Doc
          publish_branch: gh-pages
          publish_dir: ./build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com

      # 路线 B：Fine-grained PAT（推荐在组织禁用 Deploy Keys 时使用）
      - name: Publish to VoidWorks-online/web-Doc via PAT
        if: ${{ env.DEPLOY_KEY_WEBDOC == '' && env.PUBLISH_TOKEN_WEBDOC != '' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ env.PUBLISH_TOKEN_WEBDOC }}
          external_repository: VoidWorks-online/web-Doc
          publish_branch: gh-pages
          publish_dir: ./build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
